/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStocksRouteImport } from './routes/_authenticated/stocks'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPreferencesAlimentairesRouteImport } from './routes/_authenticated/preferences-alimentaires'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFitnessIndexRouteImport } from './routes/_authenticated/fitness/index'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStocksRoute = AuthenticatedStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesAlimentairesRoute =
  AuthenticatedPreferencesAlimentairesRouteImport.update({
    id: '/preferences-alimentaires',
    path: '/preferences-alimentaires',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFitnessIndexRoute =
  AuthenticatedFitnessIndexRouteImport.update({
    id: '/fitness/',
    path: '/fitness/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/fitness/': typeof AuthenticatedFitnessIndexRoute
}
export interface FileRoutesByTo {
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/': typeof AuthenticatedIndexRoute
  '/fitness': typeof AuthenticatedFitnessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/stocks': typeof AuthenticatedStocksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/fitness/': typeof AuthenticatedFitnessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index'
    | '/login'
    | '/documents'
    | '/preferences-alimentaires'
    | '/profil'
    | '/stocks'
    | '/fitness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/index'
    | '/login'
    | '/documents'
    | '/preferences-alimentaires'
    | '/profil'
    | '/stocks'
    | '/'
    | '/fitness'
  id:
    | '__root__'
    | '/_authenticated'
    | '/index'
    | '/login'
    | '/_authenticated/documents'
    | '/_authenticated/preferences-alimentaires'
    | '/_authenticated/profil'
    | '/_authenticated/stocks'
    | '/_authenticated/'
    | '/_authenticated/fitness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  Char91indexChar93Route: typeof Char91indexChar93Route
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stocks': {
      id: '/_authenticated/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedStocksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences-alimentaires': {
      id: '/_authenticated/preferences-alimentaires'
      path: '/preferences-alimentaires'
      fullPath: '/preferences-alimentaires'
      preLoaderRoute: typeof AuthenticatedPreferencesAlimentairesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fitness/': {
      id: '/_authenticated/fitness/'
      path: '/fitness'
      fullPath: '/fitness/'
      preLoaderRoute: typeof AuthenticatedFitnessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPreferencesAlimentairesRoute: typeof AuthenticatedPreferencesAlimentairesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedStocksRoute: typeof AuthenticatedStocksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFitnessIndexRoute: typeof AuthenticatedFitnessIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPreferencesAlimentairesRoute:
    AuthenticatedPreferencesAlimentairesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedStocksRoute: AuthenticatedStocksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFitnessIndexRoute: AuthenticatedFitnessIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  Char91indexChar93Route: Char91indexChar93Route,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
