/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStocksRouteImport } from './routes/_authenticated/stocks'
import { Route as AuthenticatedRlsStatusRouteImport } from './routes/_authenticated/rls-status'
import { Route as AuthenticatedRappelsRouteImport } from './routes/_authenticated/rappels'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPreferencesAlimentairesRouteImport } from './routes/_authenticated/preferences-alimentaires'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFitnessIndexRouteImport } from './routes/_authenticated/fitness/index'
import { Route as ApiPublicCalendarTokenDoticsRouteImport } from './routes/api/public/calendar.$token[.]ics'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStocksRoute = AuthenticatedStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRlsStatusRoute = AuthenticatedRlsStatusRouteImport.update({
  id: '/rls-status',
  path: '/rls-status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRappelsRoute = AuthenticatedRappelsRouteImport.update({
  id: '/rappels',
  path: '/rappels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesAlimentairesRoute =
  AuthenticatedPreferencesAlimentairesRouteImport.update({
    id: '/preferences-alimentaires',
    path: '/preferences-alimentaires',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFitnessIndexRoute =
  AuthenticatedFitnessIndexRouteImport.update({
    id: '/fitness/',
    path: '/fitness/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicCalendarTokenDoticsRoute =
  ApiPublicCalendarTokenDoticsRouteImport.update({
    id: '/api/public/calendar/$token.ics',
    path: '/api/public/calendar/$token.ics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rappels': typeof AuthenticatedRappelsRoute
  '/rls-status': typeof AuthenticatedRlsStatusRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/fitness/': typeof AuthenticatedFitnessIndexRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
}
export interface FileRoutesByTo {
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rappels': typeof AuthenticatedRappelsRoute
  '/rls-status': typeof AuthenticatedRlsStatusRoute
  '/stocks': typeof AuthenticatedStocksRoute
  '/': typeof AuthenticatedIndexRoute
  '/fitness': typeof AuthenticatedFitnessIndexRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rappels': typeof AuthenticatedRappelsRoute
  '/_authenticated/rls-status': typeof AuthenticatedRlsStatusRoute
  '/_authenticated/stocks': typeof AuthenticatedStocksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/fitness/': typeof AuthenticatedFitnessIndexRoute
  '/api/public/calendar/$token.ics': typeof ApiPublicCalendarTokenDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index'
    | '/login'
    | '/reset-password'
    | '/documents'
    | '/preferences-alimentaires'
    | '/profil'
    | '/rappels'
    | '/rls-status'
    | '/stocks'
    | '/fitness/'
    | '/api/public/calendar/$token.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/index'
    | '/login'
    | '/reset-password'
    | '/documents'
    | '/preferences-alimentaires'
    | '/profil'
    | '/rappels'
    | '/rls-status'
    | '/stocks'
    | '/'
    | '/fitness'
    | '/api/public/calendar/$token.ics'
  id:
    | '__root__'
    | '/_authenticated'
    | '/index'
    | '/login'
    | '/reset-password'
    | '/_authenticated/documents'
    | '/_authenticated/preferences-alimentaires'
    | '/_authenticated/profil'
    | '/_authenticated/rappels'
    | '/_authenticated/rls-status'
    | '/_authenticated/stocks'
    | '/_authenticated/'
    | '/_authenticated/fitness/'
    | '/api/public/calendar/$token.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  Char91indexChar93Route: typeof Char91indexChar93Route
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCalendarTokenDoticsRoute: typeof ApiPublicCalendarTokenDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stocks': {
      id: '/_authenticated/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedStocksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rls-status': {
      id: '/_authenticated/rls-status'
      path: '/rls-status'
      fullPath: '/rls-status'
      preLoaderRoute: typeof AuthenticatedRlsStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rappels': {
      id: '/_authenticated/rappels'
      path: '/rappels'
      fullPath: '/rappels'
      preLoaderRoute: typeof AuthenticatedRappelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences-alimentaires': {
      id: '/_authenticated/preferences-alimentaires'
      path: '/preferences-alimentaires'
      fullPath: '/preferences-alimentaires'
      preLoaderRoute: typeof AuthenticatedPreferencesAlimentairesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fitness/': {
      id: '/_authenticated/fitness/'
      path: '/fitness'
      fullPath: '/fitness/'
      preLoaderRoute: typeof AuthenticatedFitnessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/calendar/$token.ics': {
      id: '/api/public/calendar/$token.ics'
      path: '/api/public/calendar/$token.ics'
      fullPath: '/api/public/calendar/$token.ics'
      preLoaderRoute: typeof ApiPublicCalendarTokenDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPreferencesAlimentairesRoute: typeof AuthenticatedPreferencesAlimentairesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRappelsRoute: typeof AuthenticatedRappelsRoute
  AuthenticatedRlsStatusRoute: typeof AuthenticatedRlsStatusRoute
  AuthenticatedStocksRoute: typeof AuthenticatedStocksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFitnessIndexRoute: typeof AuthenticatedFitnessIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPreferencesAlimentairesRoute:
    AuthenticatedPreferencesAlimentairesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRappelsRoute: AuthenticatedRappelsRoute,
  AuthenticatedRlsStatusRoute: AuthenticatedRlsStatusRoute,
  AuthenticatedStocksRoute: AuthenticatedStocksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFitnessIndexRoute: AuthenticatedFitnessIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  Char91indexChar93Route: Char91indexChar93Route,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCalendarTokenDoticsRoute: ApiPublicCalendarTokenDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
