/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTropheesRouteImport } from './routes/_authenticated/trophees'
import { Route as AuthenticatedSupplementsRouteImport } from './routes/_authenticated/supplements'
import { Route as AuthenticatedSeancesRouteImport } from './routes/_authenticated/seances'
import { Route as AuthenticatedRlsStatusRouteImport } from './routes/_authenticated/rls-status'
import { Route as AuthenticatedQuetesRouteImport } from './routes/_authenticated/quetes'
import { Route as AuthenticatedProgressionRouteImport } from './routes/_authenticated/progression'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPreferencesAlimentairesRouteImport } from './routes/_authenticated/preferences-alimentaires'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedCorpsRouteImport } from './routes/_authenticated/corps'
import { Route as AuthenticatedRapportsIndexRouteImport } from './routes/_authenticated/rapports/index'
import { Route as AuthenticatedFitnessIndexRouteImport } from './routes/_authenticated/fitness/index'
import { Route as AuthenticatedRapportsIdRouteImport } from './routes/_authenticated/rapports/$id'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTropheesRoute = AuthenticatedTropheesRouteImport.update({
  id: '/trophees',
  path: '/trophees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupplementsRoute =
  AuthenticatedSupplementsRouteImport.update({
    id: '/supplements',
    path: '/supplements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeancesRoute = AuthenticatedSeancesRouteImport.update({
  id: '/seances',
  path: '/seances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRlsStatusRoute = AuthenticatedRlsStatusRouteImport.update({
  id: '/rls-status',
  path: '/rls-status',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuetesRoute = AuthenticatedQuetesRouteImport.update({
  id: '/quetes',
  path: '/quetes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressionRoute =
  AuthenticatedProgressionRouteImport.update({
    id: '/progression',
    path: '/progression',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesAlimentairesRoute =
  AuthenticatedPreferencesAlimentairesRouteImport.update({
    id: '/preferences-alimentaires',
    path: '/preferences-alimentaires',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorpsRoute = AuthenticatedCorpsRouteImport.update({
  id: '/corps',
  path: '/corps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRapportsIndexRoute =
  AuthenticatedRapportsIndexRouteImport.update({
    id: '/rapports/',
    path: '/rapports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFitnessIndexRoute =
  AuthenticatedFitnessIndexRouteImport.update({
    id: '/fitness/',
    path: '/fitness/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRapportsIdRoute = AuthenticatedRapportsIdRouteImport.update({
  id: '/rapports/$id',
  path: '/rapports/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/corps': typeof AuthenticatedCorpsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/quetes': typeof AuthenticatedQuetesRoute
  '/rls-status': typeof AuthenticatedRlsStatusRoute
  '/seances': typeof AuthenticatedSeancesRoute
  '/supplements': typeof AuthenticatedSupplementsRoute
  '/trophees': typeof AuthenticatedTropheesRoute
  '/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/fitness/': typeof AuthenticatedFitnessIndexRoute
  '/rapports/': typeof AuthenticatedRapportsIndexRoute
}
export interface FileRoutesByTo {
  '/confidentialite': typeof ConfidentialiteRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/corps': typeof AuthenticatedCorpsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/quetes': typeof AuthenticatedQuetesRoute
  '/rls-status': typeof AuthenticatedRlsStatusRoute
  '/seances': typeof AuthenticatedSeancesRoute
  '/supplements': typeof AuthenticatedSupplementsRoute
  '/trophees': typeof AuthenticatedTropheesRoute
  '/': typeof AuthenticatedIndexRoute
  '/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/fitness': typeof AuthenticatedFitnessIndexRoute
  '/rapports': typeof AuthenticatedRapportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/corps': typeof AuthenticatedCorpsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/preferences-alimentaires': typeof AuthenticatedPreferencesAlimentairesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/progression': typeof AuthenticatedProgressionRoute
  '/_authenticated/quetes': typeof AuthenticatedQuetesRoute
  '/_authenticated/rls-status': typeof AuthenticatedRlsStatusRoute
  '/_authenticated/seances': typeof AuthenticatedSeancesRoute
  '/_authenticated/supplements': typeof AuthenticatedSupplementsRoute
  '/_authenticated/trophees': typeof AuthenticatedTropheesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rapports/$id': typeof AuthenticatedRapportsIdRoute
  '/_authenticated/fitness/': typeof AuthenticatedFitnessIndexRoute
  '/_authenticated/rapports/': typeof AuthenticatedRapportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/index'
    | '/login'
    | '/reset-password'
    | '/corps'
    | '/documents'
    | '/nutrition'
    | '/preferences-alimentaires'
    | '/profil'
    | '/progression'
    | '/quetes'
    | '/rls-status'
    | '/seances'
    | '/supplements'
    | '/trophees'
    | '/rapports/$id'
    | '/fitness/'
    | '/rapports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/confidentialite'
    | '/index'
    | '/login'
    | '/reset-password'
    | '/corps'
    | '/documents'
    | '/nutrition'
    | '/preferences-alimentaires'
    | '/profil'
    | '/progression'
    | '/quetes'
    | '/rls-status'
    | '/seances'
    | '/supplements'
    | '/trophees'
    | '/'
    | '/rapports/$id'
    | '/fitness'
    | '/rapports'
  id:
    | '__root__'
    | '/_authenticated'
    | '/confidentialite'
    | '/index'
    | '/login'
    | '/reset-password'
    | '/_authenticated/corps'
    | '/_authenticated/documents'
    | '/_authenticated/nutrition'
    | '/_authenticated/preferences-alimentaires'
    | '/_authenticated/profil'
    | '/_authenticated/progression'
    | '/_authenticated/quetes'
    | '/_authenticated/rls-status'
    | '/_authenticated/seances'
    | '/_authenticated/supplements'
    | '/_authenticated/trophees'
    | '/_authenticated/'
    | '/_authenticated/rapports/$id'
    | '/_authenticated/fitness/'
    | '/_authenticated/rapports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trophees': {
      id: '/_authenticated/trophees'
      path: '/trophees'
      fullPath: '/trophees'
      preLoaderRoute: typeof AuthenticatedTropheesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supplements': {
      id: '/_authenticated/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof AuthenticatedSupplementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seances': {
      id: '/_authenticated/seances'
      path: '/seances'
      fullPath: '/seances'
      preLoaderRoute: typeof AuthenticatedSeancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rls-status': {
      id: '/_authenticated/rls-status'
      path: '/rls-status'
      fullPath: '/rls-status'
      preLoaderRoute: typeof AuthenticatedRlsStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quetes': {
      id: '/_authenticated/quetes'
      path: '/quetes'
      fullPath: '/quetes'
      preLoaderRoute: typeof AuthenticatedQuetesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progression': {
      id: '/_authenticated/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof AuthenticatedProgressionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences-alimentaires': {
      id: '/_authenticated/preferences-alimentaires'
      path: '/preferences-alimentaires'
      fullPath: '/preferences-alimentaires'
      preLoaderRoute: typeof AuthenticatedPreferencesAlimentairesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corps': {
      id: '/_authenticated/corps'
      path: '/corps'
      fullPath: '/corps'
      preLoaderRoute: typeof AuthenticatedCorpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/': {
      id: '/_authenticated/rapports/'
      path: '/rapports'
      fullPath: '/rapports/'
      preLoaderRoute: typeof AuthenticatedRapportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fitness/': {
      id: '/_authenticated/fitness/'
      path: '/fitness'
      fullPath: '/fitness/'
      preLoaderRoute: typeof AuthenticatedFitnessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rapports/$id': {
      id: '/_authenticated/rapports/$id'
      path: '/rapports/$id'
      fullPath: '/rapports/$id'
      preLoaderRoute: typeof AuthenticatedRapportsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCorpsRoute: typeof AuthenticatedCorpsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedPreferencesAlimentairesRoute: typeof AuthenticatedPreferencesAlimentairesRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProgressionRoute: typeof AuthenticatedProgressionRoute
  AuthenticatedQuetesRoute: typeof AuthenticatedQuetesRoute
  AuthenticatedRlsStatusRoute: typeof AuthenticatedRlsStatusRoute
  AuthenticatedSeancesRoute: typeof AuthenticatedSeancesRoute
  AuthenticatedSupplementsRoute: typeof AuthenticatedSupplementsRoute
  AuthenticatedTropheesRoute: typeof AuthenticatedTropheesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRapportsIdRoute: typeof AuthenticatedRapportsIdRoute
  AuthenticatedFitnessIndexRoute: typeof AuthenticatedFitnessIndexRoute
  AuthenticatedRapportsIndexRoute: typeof AuthenticatedRapportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCorpsRoute: AuthenticatedCorpsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedPreferencesAlimentairesRoute:
    AuthenticatedPreferencesAlimentairesRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedProgressionRoute: AuthenticatedProgressionRoute,
  AuthenticatedQuetesRoute: AuthenticatedQuetesRoute,
  AuthenticatedRlsStatusRoute: AuthenticatedRlsStatusRoute,
  AuthenticatedSeancesRoute: AuthenticatedSeancesRoute,
  AuthenticatedSupplementsRoute: AuthenticatedSupplementsRoute,
  AuthenticatedTropheesRoute: AuthenticatedTropheesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRapportsIdRoute: AuthenticatedRapportsIdRoute,
  AuthenticatedFitnessIndexRoute: AuthenticatedFitnessIndexRoute,
  AuthenticatedRapportsIndexRoute: AuthenticatedRapportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
