-- =====================================================================
-- No-op (25/07/2026) : ce fichier était un DOUBLON byte-pour-byte de
-- 20260723160000_document_deposit_pipeline.sql (diff confirmé — seule
-- différence, une fin de ligne). L'original du 23/07 a déjà été appliqué
-- avec succès et est enregistré dans schema_migrations ; c'est lui qui a
-- déversé `documents.analysis` dans `extracted_items` et retiré la
-- colonne. Ce doublon, jamais appliqué (bloqué dès la première ligne par
-- `ERROR: column "analysis" does not exist`, puisque l'original avait
-- déjà retiré cette colonne), bloquait le pipeline CI "Supabase
-- Migrations". Neutralisé plutôt que supprimé (garde-fou pre-commit :
-- une migration ne se supprime jamais, cf. `supabase migration repair`)
-- — conservé comme trace d'audit, sans aucun effet.
-- =====================================================================
SELECT 1;
