ALTER TABLE public.items
  ADD COLUMN IF NOT EXISTS room TEXT,
  ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER,
  ADD COLUMN IF NOT EXISTS calories_per_100g NUMERIC,
  ADD COLUMN IF NOT EXISTS protein_per_100g NUMERIC,
  ADD COLUMN IF NOT EXISTS carbs_per_100g NUMERIC,
  ADD COLUMN IF NOT EXISTS fat_per_100g NUMERIC,
  ADD COLUMN IF NOT EXISTS fiber_per_100g NUMERIC,
  ADD COLUMN IF NOT EXISTS sugar_per_100g NUMERIC,
  ADD COLUMN IF NOT EXISTS sodium_per_100g NUMERIC;

CREATE INDEX IF NOT EXISTS idx_items_room ON public.items(room);